title: ERIC J. CHAN # your name (or website title) here
logo: "/images/cashbot2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <img src="images/certified.png" height="50px" >
  <br>
  @Applying Data Science and Machine Learning to Industry !!! <br>Seeking full-time Employment Opportunities!!!     
  <br><br>
  <a href="https://www.linkedin.com/in/eric-j-chan-37068b60/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://sites.google.com/site/echanj">View My Online Research Pages</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-0MB2DBX159 # your Google Analytics tracking ID here
